# 

In [27]:
import numpy as np

In [28]:
def gen_vander_matrix(input_vector, n, increasing=False):
    
    if not increasing:
        output_matx = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        output_matx = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return output_matx

In [29]:
inputvector = np.array([1,3,5,7,9])
Output_columns = 3
output_matx_dec_order = gen_vander_matrix(inputvector,Output_columns,False)
output_matx_inc_order = gen_vander_matrix(inputvector,Output_columns,True)

In [30]:
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",Output_columns,"\n")
print("Vander matrix in decreasing order of powers:\n\n",output_matx_dec_order,"\n")
print("Vander matrix in increasing order of powers:\n\n",output_matx_inc_order,"\n")

The input array is: [1 3 5 7 9] 

Number of columns in output matrix should be: 3 

Vander matrix in decreasing order of powers:

 [[ 1  1  1]
 [ 9  3  1]
 [25  5  1]
 [49  7  1]
 [81  9  1]] 

Vander matrix in increasing order of powers:

 [[ 1  1  1]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  7 49]
 [ 1  9 81]] 



In [31]:
inputvector = np.array([2,4,6,8,10])
Output_columns = 5
output_matx_dec_order = gen_vander_matrix(inputvector,Output_columns,False)
output_matx_inc_order = gen_vander_matrix(inputvector,Output_columns,True)

In [32]:
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",Output_columns,"\n")
print("Vander matrix in decreasing order of powers:\n\n",output_matx_dec_order,"\n")
print("Vander matrix in increasing order of powers:\n\n",output_matx_inc_order,"\n")

The input array is: [ 2  4  6  8 10] 

Number of columns in output matrix should be: 5 

Vander matrix in decreasing order of powers:

 [[   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix in increasing order of powers:

 [[    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]] 



#  2. Problem Statement
 ##Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th
moving
 average of the given sequence is defined as follows:
 The moving average sequence has n-k+1 elements as shown below.
 The moving averages with k=4 of a ten-value sequence (n=10) is shown below
 i 1 2 3 4 5 6 7 8 9 10
 ===== == == == == == == == == == ==
 Input 10 20 30 40 50 60 70 80 90 100
 y1 25 = (10+20+30+40)/4
 y2 35 = (20+30+40+50)/4
 y3 45 = (30+40+50+60)/4
 y4 55 = (40+50+60+70)/4
 y5 65 = (50+60+70+80)/4
 y6 75 = (60+70+80+90)/4
 y7 85 = (70+80+90+100)/4
 Thus, the moving average sequence has n-k+1=10-4+1=7 values.
 Problem Statement
 Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [33]:
def moving_average(x, n=3) :
    x_sum = np.cumsum(x, dtype=float)
    x_sum[n:] = x_sum[n:] - x_sum[:-n]
    return x_sum[n - 1:] / n

In [34]:
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
x1=np.array(x)
np.array(moving_average(x1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])